modLoader="javafml"
loaderVersion="[47,)"
license="MIT"
[[mods]]
modId="lom_no_minecolonies_worldgen"
version="0.1.0"
displayName="LoM - Disable MineColonies Worldgen"
authors="LoM (based on Hamderber)"
description='''Disables natural MineColonies abandoned settlement structure sets. Player-created colonies still work.'''
[[dependencies.lom_no_minecolonies_worldgen]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"
[[dependencies.lom_no_minecolonies_worldgen]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.20.2)"
ordering="NONE"
side="BOTH"
